### PR TITLE
fix: Fixes github issue #745

### LINKED ISSUE #745: Bug introduced by #732 - "Invalid Scheme"
The method used to fix #732 has caused an "invalid scheme" error when using this library inside of Cordova because it calls "window.open" with an empty string before setting the "location.href" of the popup which Cordova doesn't seem to like.

I know that Cordova should allow for "window.open" with an empty string, but it doesn't and getting them to fix that issue will be a very major change.

This fix could have been made much simpler. I will submit a PR that simplifies the fix and prevents the error from occurring in Cordova.

### PR DESCRIPTION
**Pull request by yinzara**
### Description

This PR provides a simpler fix for #732 that doesn't break Cordova builds.

### References

Fixes #745 

### Testing
Prior tests added for #732 address confirming this fix still works

### CODE REVIEW

**Review by stevehobbsdev — CHANGES_REQUESTED** [review]
Hi @yinzara,

Thanks for submitting this PR. Unfortunately with this change in place, it completely reverts the fix in #732, which was a fix so that popups were no longer blocked in Safari and Firefox. With your change in place, these popups are once again blocked, and so I cannot accept the PR as it is now.

The crux of the issue (and why it looks unnecessarily complex at first glance) is that `openPopup` is called before this line:

```js
const code_challengeBuffer = await sha256(code_verifier);
```

The `await` is causing an issue here because it then puts it into an asynchronous context, and these browsers no longer see the opening of the pop as coming from the result of a user action, and they get blocked. But we need that call to happen so that the URL can be built and supplied to the popup.

I do appreciate it causes problems on the Cordova platform. I'd be happy to accept a PR that continued to allow popups to work in these browsers while achieving the desired outcome for Cordova.

When resubmitting the PR for review, please consider:

* The unit tests should continue to pass (currently they don't)
* New tests should be added to cover your additional functionality
* Please ensure popups are not blocked in Safari and Firefox with your changes - you can test this using the Playground (`npm start`) and using the "Login with Popup" button
* Let us know how we can test this in Cordova. Better yet, supply a small repro app

Let me know if I can help further.

**Comment by yinzara** [comment]
Apologies. I was not aware that was the cause (I thought it was "runPopup" being async).

I was able to find a simple dependency `crypto-digest-sync`, that can do sha256 crypto digests synchronously.  It adds less than 1k to the total package size as well and allows us to simplify its support (doesn't have IE 11 issues).  

If you want, I could move the code out of the dependency (as its only one file that matters) directly into auth0-spa-js if it would make you more apt to accept it.  It uses the MIT license so it's allowed.

I've updated unit tests to reflect the change.

Thoughts?

**Comment by stevehobbsdev** [comment]
@yinzara Thanks for progressing the PR. My thoughts are that we would not like to take a dependency on this package especially for crypto, and moving that code out feels like a sledgehammer approach to this problem. At the end of the day we'd like to continue to rely on the browser's native Crypto implementation. I would encourage you to continue to develop an alternative solution if possible.

One thing I wanted to ask; I'm curious about the need to use `loginWithPopup` here for Cordova - is there a reason you cannot use `loginWithRedirect`? The login pages (either the classic or the new login experience) both have mobile-friendly views.

**Comment by stevehobbsdev** [comment]
@yinzara Please let me know whether you will be progressing this PR or if we can close - thanks.

**Comment by stevehobbsdev** [comment]
Closing for now, but if this is to be progressed, please re-open.

**Pull request closed without merging**
