### PR TITLE
feat(ClientStorage#remove):added support of cookieDomain

### PR DESCRIPTION
**Pull request by Dannnir**
### Changes

Auth0 support setting the cookieDomain for the Auth0Client, unfortunately we are missing implematention of removing from the same domain, this PR adds this implemantation at the storage level

### Testing

- [ ] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [ ] This change has been tested on the latest version of the platform/language

### Checklist

- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ ] All code quality tools/guidelines have been run/followed

### CODE REVIEW

**Comment by Dannnir** [comment]
Hi @evansims, I see you added support of Semgret (which I'm not familiar with), it fails on login issue, should I do something?
Thanks!

**Comment by evansims** [comment]
Hey @Dannnir 👋 No worries, Semgrep failing for forked repos is a known issue for us, since forks can't see our secrets for it to run successfully. We're investigating some solutions for this but, for the moment, you can safely ignore that status check failing. Thanks!

**Comment by stevehobbsdev** [comment]
Thanks for the contribution @Dannnir - can you please fill out the description in the template and describe a bit more about the PR?

Also there is a test failing that we'd need fixed up. Could you take a look?

**Comment by Dannnir** [comment]
@stevehobbsdev done 👍 
Can you approve? + how can I check it in my app?   not sure how to publish a snapshot version

**Comment by stevehobbsdev** [comment]
Thanks for fixing it up @Dannnir, I'll take a look this week.

To test a snapshot version, the easiest way I've found is to use `npm pack` within your locally-cloned version of the repo with your changes to generate a `.tar.gz` archive of the package, then `npm install <path to .tar.gz>` this into the app you want to test it in. You might need to manually change the package version inside 'package.json` to something unique if you already have the latest version of the package installed in your app.

You might also be able to use [`npm link`](https://docs.npmjs.com/cli/v8/commands/npm-link) to achieve a similar thing, but I tend to run into issues with it so default to using `npm pack` these days.

**Review by stevehobbsdev — APPROVED** [review]

**Pull request merged**
