### PR TITLE
Handle oauth/token request errors

### PR DESCRIPTION
**Pull request by luisrudge**
### Description

Our http request library doesn't throw an error if the request is 401, 403 etc, so it's up to us to implement the error handling logic. This PR adds logic to catch unsuccessful requests (non 2xx status code) and throws the appropriate error to inform developers what's going on.

### References

This greatly improves DX when dealing with issues like https://github.com/auth0/auth0-spa-js/issues/70

### Testing

- [x] This change adds test coverage for new/changed/fixed functionality

### CODE REVIEW

**Comment by damieng** [comment]
Is this a breaking change?

Presumably at a min bar we need to update the docs and quickstarts to show error handling.

**Comment by luisrudge** [comment]
@damieng no. before, it would just throw a cryptic error like this:
image

Now it will throw an actual method with error and error_description. This actually makes it work with any error handling you already had in place.

**Comment by JohnnyTMD** [comment]
Hi, I still get this error.
I'm using the latest version, the token is ok. The error is thrown by this method auth0.handleRedirectCallback() 
I guess it is just a typo, the actual field name in the request is access_token, in the library I can see it's searching for id_token.
jwt.ts:37
Screenshot from 2019-08-29 21-46-22

**Comment by luisrudge** [comment]
That's super weird. Means that the HTTP request is ok, but you're not getting the id_token 🤔 can you please send a HAR request to luis.rudge@auth0.com? I'll investigate.

**Comment by JohnnyTMD** [comment]
I have solved the issue, @luisrudge helped me with that.
In case you wonder, the issue was caused by a custom rule, so I have disabled it and after that it worked.

**Comment by luisrudge** [comment]
Perfect @JohnnyTMD. Can you figure it out what in the rule was removing the id_token from the response?

**Pull request merged**
