### PR TITLE
[SDK-1159] Use generics for getUser

### PR DESCRIPTION
**Pull request by frederikprijck**
This PR allows the consumer of the API to pass a generic type to the `getUser` method:

Instead of doing:

```
const user: MyUser = await auth0.getUser();
```

users can now use

```
const user = await auth0.getUser<MyUser>();
```

When the generic is omitted, any is still being used.

**Note**: This does not change anything to our internal typing of the User object, as this can be very different for every application, we are still using any for this.

### CODE REVIEW

**Review by stevehobbsdev — APPROVED** [review]

**Comment by stevehobbsdev** [comment]
Just a quick Q - from our internal conversation, going back to your point about internally typing a user, do we want to provide any standard type here that developers using the SDK can use?

I can imagine it being `IdToken` (https://github.com/auth0/auth0-spa-js/blob/42d6f940785ddd38c7e7096bcd172753bbf2df34/src/global.ts#L431-L470) just with the non-profile claims removed and all the properties optional, with the ability to hold extra properties (so keep the `[key: string]: any` prop).

I agree that this change isn't that valuable for us, but I think we could provide a standard type here for user profile information that the developer can use externally to save them rolling their own.

**Comment by frederikprijck** [comment]
@stevehobbsdev I added a commit to add the User type. This requires a casting in our getUser method, but improves type hinting for the user while still allowing any additional property.

I also added `sub`, which did not exist on the IdToken interface but is part of the User.

Should we add this type to our docs ?

**Comment by stevehobbsdev** [comment]
Yes I think we can add it to our docs.

**Review by stevehobbsdev — DISMISSED** [review]

**Comment by frederikprijck** [comment]
Updated the PR to include docs for the User type and reference it from the getUser method

image

**Review by stevehobbsdev — APPROVED** [review]

**Pull request merged**
