### PR TITLE
Fix popup blocker showing for loginWithPopup in Firefox & Safari

### LINKED ISSUE #726: loginWithPopup is blocked by firefox since version 1.6.5
### Describe the problem
Using loginWithPopup in firefox in an onclick works in 1.6.4. However, in 1.6.5 the same code now triggers firefox pop blocker. 

I have done some preliminary investigation and I believe the issue was introduced in [this commit](https://github.com/auth0/auth0-spa-js/pull/368/commits/6665dc071e7e27d480ef2b7d91673741fe571d5e).

Prior to this, the code would call window.open during the asynchronous part of the function call - then later, it would asynchronously set the URL of the pop up. This is the correct way to handle this. However, after the refactor the popup was moved to the asynchronous code - this causes Firefox to block it with its popup blocker. In Girefox if you try to open a window asynchronously it will [no longer be treated as a user action ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions). 

### What was the expected behavior?

The window should open without being blocked by the popup blocker.

### Reproduction

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

If so, provide steps:

Run the playground, click login with popup in firefox. Get a banner showing "firefox prevented this site from opening a pop up window". Console shows "Uncaught (in promise) Error: Could not open popup"

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**
- Listed above - any version after 1.6.4 has this issue
- 
- **Which browsers have you tested in?**
- Issue occurs in firefox
- 
- **Which framework are you using, if applicable (Angular, React, etc):**
- Vue
- 
- **Other modules/plugins/libraries that might be involved:**
None

### LINKED ISSUE #728: Cannot login if cookies are blocked using refresh tokens and local cache storage
Using the latest version 1.14.0. When I run loginwithpop up using social login (google), refresh tokens and cache set to localstorage. The login fails ,on second attempt I get this error in Safari:

[Error] TypeError: null is not an object (evaluating 't.organization')

	_callee$ (app.js:16429)
	l (chunk-vendors.js:27481:5863)
	(anonymous function) (chunk-vendors.js:27481:5648)
	asyncGeneratorStep (chunk-vendors.js:131)
	_throw (chunk-vendors.js:157)
	promiseReactionJob

In Firefox, if I set it to block all third party cookies it shows as:

TypeError: t is null
    node_modules auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js/</Vo</t.prototype.loginWithPopup/</<@http://localhost:8080/js/chunk-vendors.js:32
    s http://localhost:8080/js/chunk-vendors.js:32
    s http://localhost:8080/js/chunk-vendors.js:32
    c http://localhost:8080/js/chunk-vendors.js:32
    promise callback*a http://localhost:8080/js/chunk-vendors.js:32
    c http://localhost:8080/js/chunk-vendors.js:32
    promise callback*a http://localhost:8080/js/chunk-vendors.js:32
    c http://localhost:8080/js/chunk-vendors.js:32
    promise callback*a http://localhost:8080/js/chunk-vendors.js:32
    r http://localhost:8080/js/chunk-vendors.js:32
    r http://localhost:8080/js/chunk-vendors.js:32
    node_modules auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js/</Vo</t.prototype.loginWithPopup@http://localhost:8080/js/chunk-vendors.js:32
    _callee$ http://localhost:8080/js/app.js:17333
    l http://localhost:8080/js/chunk-vendors.js:36663
    _invoke http://localhost:8080/js/chunk-vendors.js:36663
    t http://localhost:8080/js/chunk-vendors.js:36663
    asyncGeneratorStep http://localhost:8080/js/chunk-vendors.js:131
    _next http://localhost:8080/js/chunk-vendors.js:153
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:160
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:149
    loginWithPopup http://localhost:8080/js/app.js:17364
    _callee$ http://localhost:8080/js/app.js:1220
    l http://localhost:8080/js/chunk-vendors.js:36663
    _invoke http://localhost:8080/js/chunk-vendors.js:36663
    t http://localhost:8080/js/chunk-vendors.js:36663
    asyncGeneratorStep http://localhost:8080/js/chunk-vendors.js:131
    _next http://localhost:8080/js/chunk-vendors.js:153
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:160
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:149
    loginClick http://localhost:8080/js/app.js:1231
    click http://localhost:8080/js/app.js:7562
    invokeWithErrorHandling http://localhost:8080/js/chunk-vendors.js:38806
    invoker http://localhost:8080/js/chunk-vendors.js:39131
    invokeWithErrorHandling http://localhost:8080/js/chunk-vendors.js:38806
    $emit http://localhost:8080/js/chunk-vendors.js:40835
    click http://localhost:8080/js/chunk-vendors.js:47527
    invokeWithErrorHandling http://localhost:8080/js/chunk-vendors.js:38806
    invoker http://localhost:8080/js/chunk-vendors.js:39131
    _wrapper http://localhost:8080/js/chunk-vendors.js:43860

How can I troubleshoot this? Am I doing something wrong? 

My main goal is to allow logins using safari. All the posts on this issue says to use refresh tokens  and set cache to localstorage, however that doesn't seem to be working with Google OAuth login.

### PR DESCRIPTION
**Pull request by stevehobbsdev**
This PR moves the creation of the popup window in `loginWithPopup` outside of an async context, so that browsers like Firefox and Safari don't attempt to block the popup as it will now come directly from a user interaction event.

It achieves this by moving popup creation into `loginWithPopup` itself instead of inside `runPopup`.

This PR also fixes an issue where calling `loginWithPopup(null)` would cause the method to crash when it tried to access `options.organization`. It does this by making the parameters optional, instead of providing default values (which are now assigned inside the method).

Fixes #726
Fixes #728

### CODE REVIEW

**Review by frederikprijck — APPROVED** [review]

**Comment by someone1** [comment]
I was interested in learning how you implemented this as we worked around some popup/cookie issues using custom Auth0 domains and such, and noticed one small thing that may not even be an issue. 

I see that the popup is initialized and navigated to prior to a message event listener being setup. Though I doubt devices would complete the Auth0 process faster than they get around to setting up the event listener, it seemed like something a reordering of some code could fix - setting up the event listener before initiating the task that will send an event.

Just thought I'd mention it!

**Comment by stevehobbsdev** [comment]
Yes it's a good catch. Unlikely to cause a real issue but I will look at refactoring that - thanks

**Comment by shan-du** [comment]
Hi @stevehobbsdev 

I've encountered an issue with `getTokenWithPopup`, which calls `loginWithPopup`.  
For some users, somehow their browsers were still blocking the popup for some reason, and when they ignore or deny the popup, then `config.popup` will be a null object and throws a null pointer exception.  

I think the code is not handling this case, see line 345 ~ 369 of `Auth0Client.ts`

```javascript
    if (!config.popup) {
      config.popup = openPopup('');
    }

    ...

    config.popup.location.href = url; // <-- this would cause exception if popup is undefined
```


We had to do a string match to treat this exception in our code but that's very hacky imo, perhaps you guys could catch this error (e.g. `popup` being null) on your end & reject with a specific error type?

**Comment by frederikprijck** [comment]
Wouldnt it make sense for your application to ensure you don't use `getTokenWithPopup` when the user has popups blocked? I believe it would avoid any error...

That said, I agree we should probably throw a more explicit error in this case, but I would still try and avoid calling it when popups are blocked.

**Comment by shan-du** [comment]
@frederikprijck yep yep 💯 i'm actually trying to implement this fix exactly like you mentioned right now by doing a popup detection first before calling that method, & give user a visible notification if the popup is blocked.

but also like you said, this was def a missed case & it should be throwing an explicit error (e.g. `PopupCancelledError`)

**Pull request merged**
