### PR TITLE
update(Auth0Client):added cookieDomain to _processOrgIdHint

### PR DESCRIPTION
**Pull request by Dannnir**
### Changes
added cookieDomain configuration to OrgId cookie hint

### References
https://github.com/auth0/auth0-spa-js/pull/885

### Testing

- [ ] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [ ] This change has been tested on the latest version of the platform/language

### Checklist

- [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ ] All code quality tools/guidelines have been run/followed

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Looks good, thanks for the contribution. If you can add unit tests around this I'd be happy to review and approve.

**Comment by Dannnir** [comment]
Thanks @stevehobbsdev, done

**Comment by Dannnir** [comment]
@stevehobbsdev

**Review by stevehobbsdev — APPROVED** [review]

**Comment by stevehobbsdev** [comment]
Thanks for the contribution!

**Comment by Dannnir** [comment]
@stevehobbsdev Can we push a new release tag for this one?

**Comment by stevehobbsdev** [comment]
Yes, a new release will be pushed out next week.

**Pull request merged**
