### PR TITLE
Update typescript definition for max_age param

### PR DESCRIPTION
**Pull request by lbalmaceda**
`max_age` should be a number (represents seconds). Unless this is needed as a string for any other reason, this PR should fix that.

### CODE REVIEW

**Comment by lbalmaceda** [comment]
_7 months ago._ 😬 I'll follow your suggestion.
Didn't know types had tests. I'm fixing this as we speak.

**Comment by stevehobbsdev** [comment]
@damieng Interesting point about the breaking change - this was shipped earlier today

**Comment by luisrudge** [comment]
I think we're fine changing this to `number` right now because we *just* released this change as part of the OIDC compliance PR: https://github.com/auth0/auth0-spa-js/pull/248/files#diff-bea166de5e48cc5e984d359640eb357eR243

**Comment by luisrudge** [comment]
@lbalmaceda can you rollback the last change and just use number + fix tests instead?

**Comment by lbalmaceda** [comment]
`max_age` for the JWT verification options was shipped today and incorrectly set to string. That can be changed because it's private and not directly set by the user. However, the `max_age` param for the `BaseLoginOptions` was set ~7 months ago thus we need to do as Damien suggested and consider both scenarios. I've added a function to parse a possible string value and default to undefined when can't be parsed.

**Comment by luisrudge** [comment]
@lbalmaceda ahhhh. gotcha!

**Pull request merged**
