### PR TITLE
fix: add missing types to utils.ts and errors.ts

### PR DESCRIPTION
**Pull request by SeyyedKhandon**
### Description

I've added some missing types to utils.ts.

### CODE REVIEW

**Comment by SeyyedKhandon** [comment]
`MessagePort` types are available  within `node_modules/typescript/lib/lib.dom.d.ts` or `node_modules/typescript/lib/lib.webworker.d.ts`

**Comment by stevehobbsdev** [comment]
Thanks @SeyyedKhandon  - we're seeing build failures with these changes, are you able to take a look?

**Comment by SeyyedKhandon** [comment]
@stevehobbsdev, it's done. could you have a look?

**Review by stevehobbsdev — APPROVED** [review]
Looks good @SeyyedKhandon - thanks!

**Comment by SeyyedKhandon** [comment]
you're welcome😉

**Pull request merged**
