### PR TITLE
Fix - openPopup with an empty string doesn't work in Outlook (through Edge)

### PR DESCRIPTION
**Pull request by hay12396**
### Changes
My company is building an Outlook Addon (which uses Edge behind the scenes), the `loginWithPopup` function in the package first opens an empty tab and then assigns a URL to it.
This doesn't work in Outlook - the actual result is that Outlook asks you to choose a windows program to open a file named "about: blank" which doesn't have any extension
I have made a change that fixes the issue which is essentially just a small rearrangement of the code in the function so that it will open the tab with a URL.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All code quality tools/guidelines have been run/followed

### CODE REVIEW

**Review by frederikprijck — CHANGES_REQUESTED** [review]
Thanks for your changes.
Even though we very much appreciate the effort, It helps to open issues before diving into making actual changes.

The changes in this PR might revert the fix that was introduced as part of https://github.com/auth0/auth0-spa-js/pull/732, so we will need to ensure we come up with a solution that doesn't change the behavior of that fix.

**Comment by stevehobbsdev** [comment]
@hay12396 Indeed the changes you've made present an issue in some browsers as with this configuration, they no longer see the popup being opened as a result user interaction (thanks to [the await](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L474)) and will instead attempt to block it.

Outlook Addons isn't a primary use case we optimize for but happy to consider a PR that works in both scenarios, if you'd like to propose further changes.

**Comment by jasonnutter** [comment]
Some perspective from MSAL.js: we decided that to properly support both scenarios (browsers like Safari where popups opened asynchronously could be blocked, and environments like Office Addins where opening a popup with `about:blank` isn't supported), we had to make the behavior configurable by the application (i.e. a flag that controls how the popup is opened). We couldn't figure out a way to support both scenarios simultaneously.

**Comment by stevehobbsdev** [comment]
@jasonnutter Thanks for that, that's very useful insight 🎉

**Comment by evansims** [comment]
Going to close this PR as discussion appears to have gone quiet. If you'd like to return to discussing the enhancement further, let's reboot this by opening an issue first where we can iron out implementation details. We can always re-open this PR later as the need warrants. Thank you all for your contributions.

**Pull request closed without merging**
