### PR TITLE
Include typescript exports

### PR DESCRIPTION
**Pull request by felipeleusin**
### Description

This PR includes the exports of the typescript typings from the index.d.ts file. With this you can access all the typings directly from the package.

For example:

```
import createAuth0Client, { Auth0ClientOptions } from "@auth0/auth0-spa-js";
```

One downside is that you need to access the exported types directly inside the project but this is something I consider a acceptable and provides more clarity as to where the types are coming from.

I also renamed `getIdTokenClaimsOptions` to `GetIdTokenClaimsOptions` but kept an export with the old name for compatibility sake so this doesn't need to qualify as breaking change.

### References

Issues: #63, #39

### CODE REVIEW

**Comment by luisrudge** [comment]
@felipeleusin thanks for the PR 🎉 can you please check why integration tests are failing? I assume it's related to how the imports work?

**Comment by joshcanhelp** [comment]
@felipeleusin - Are you able to take a look at the failing tests here? Thank you in advance 🙇

**Comment by felipeleusin** [comment]
Hi sorry, still couldn't but I will be able to take a look at this next week

**Comment by felipeleusin** [comment]
Hi, just wanted to say that I'm switching jobs and won't be working with this library anymore so if anyone feels like picking this up, feel free

**Comment by frbar** [comment]
Hi, if it can be of any help... by adding `default` it works. Couldn't find a wait to fix the export and still having both tests and integration tests running fine.

https://github.com/felipeleusin/auth0-spa-js/pull/1

**Comment by stevehobbsdev** [comment]
Closing this in favour of #310

**Comment by felipeleusin** [comment]
Thanks for picking this up. Sorry I couldn't finish the PR

**Pull request closed without merging**
