### PR TITLE
feat: 🎸 Add `nonce` override to `buildAuthorizeUrl`

### PR DESCRIPTION
**Pull request by willhackett**
### Description

Supplying a `nonce` will override the generated value stored in the
transaction prior to construction of the authorize URL. This may be
useful for systems where the webserver provides a value for CSRF
protection that may need to be correlated to Auth0 events.

The `nonce` can now be optionally supplied to the `loginWithRedirect`, `loginWithPopup` and `buildAuthorizeUrl` methods.

### References

- [Persist nonce across requests](https://auth0.com/docs/api-auth/tutorials/nonce#persist-nonces-across-requests)

### Testing

Supply a `nonce` value to one of the methods making use of `buildAuthorizeUrl`. The `nonce` is then stored in the transaction manager.

-  ~~I have added documentation for new/changed functionality in this PR or in auth0.com/docs~~
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by willhackett** [comment]
@stevehobbsdev just a couple of questions around this too:

- Would you recommend continuing to base64 encode the `nonce` even if it's manually provided?
- Should providing a `nonce` change the functionality of the `TransactionManager` and validate the persisted value against a value provided in the `Auth0ClientOptions`?

**Comment by stevehobbsdev** [comment]
@willhackett Thanks for raising. I'm interested in learning more about the use-case here. Why override `nonce` instead of providing a custom param that you can put into a token using a custom rule?

**Comment by willhackett** [comment]
The scenario is the reverse, the web server provides a session ID that must become available in a rule. It's fairly typical to have a cookie-based Session ID or CSRF Token.

We'd like to pass this value to Auth0 for the initial login and all subsequent token fresh events.

**Comment by stevehobbsdev** [comment]
> We'd like to pass this value to Auth0 for the initial login and all subsequent token refresh events instead of the nonce generated in the client-side prior to the initial login event.

To be clear, you can already pass a custom value to Auth0 and pick it up in a custom rule, unless I'm still not understanding. You can do this:

```js
loginWithRedirect({
   customProp: 'my custom value'
});
```

And then use a rule to add this to a token:

```js
function (user, context, callback) {
  // TODO: implement your rule
  const namespace = 'http://domain.com/';

  let idTokenClaims = context.idToken || {};
  let accessTokenClaims = context.accessToken || {};

  idTokenClaims[namespace + 'custom'] = context.request.query.customProp;
  context.idToken = idTokenClaims;

  callback(null, user, context);
}
```

I'm not sure why you want to override `nonce` specifically. Are you saying that your session ID or CSRF token will be different per-request? Because it should be different every request to help mitigate against replay attacks.

**Comment by willhackett** [comment]
Closing as we've validated the additional query params are accepted.

**Pull request closed without merging**
