### PR TITLE
Customize defaultScope used by auth0Client

### PR DESCRIPTION
**Pull request by srihari93**
### Description

The library includes `'openid profile email'` as defaultScope and there is no way for devs to exclude these scopes. Some of our users have lot of unnecessary information in `profile` and their JWT tokens too big to fit in the `Authorization` header. We would like to have the flexibility to exclude some scopes, as we have with the auth0-lock.js.

The maintainers suggested that a `advancedScope.defaultScope` can be used to control defaultScope for cases like us but, keep the default behaviour for other devs. This is an acceptable solution to us and this PR implements the suggestion.
```
const auth0 = await createAuth0Client({
  client_id: 'cid',
  domain: 'domain.auth0.com',
  advancedOptions: {
    defaultScope: 'openid'
  }
})
```
The Docs should be changed to add this info.

### References
- https://github.com/auth0/auth0-spa-js/issues/228#issuecomment-595116426
- https://github.com/auth0/auth0-spa-js/issues/228#issuecomment-595123093

### Testing
A simple test is added, please see if thats enough https://github.com/srihari93/auth0-spa-js/blob/a2fc948757362de2bdb3d05f661cd6304fbaacc5/__tests__/index.test.ts#L187-L203

### Checklist
- [x] I have added documentation for new/changed functionality in this PR description
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Thanks for this @srihari93.

We will need additional tests that cover the other entry points into the SDK that deal with default scopes. I see you've provided a test for `getIdTokenClaims`, we will need equivalent tests for:

* `getTokenSilently`
* `loginWithRedirect`
* `getUser`
* `getTokenWithPopup`
* `loginWithPopup`
* `buildAuthorizeUrl`

These all process default scopes, either by calling `getUniqueScopes` directly or through `_getParams`.

**Comment by damieng** [comment]
I think we also want to force `openId` to always be included as well as part of our OIDC Compliance push.

**Comment by stevehobbsdev** [comment]
@srihari93 As mentioned above, we would need additional tests written plus we need to enforce `openid` even if the developer specifies other defaults.

This could be done in the constructor here, for example.

```js
this.defaultScope = getUniqueScopes(`openid 
      ${
        this.options.advancedOptions &&
        this.options.advancedOptions.defaultScope
          ? this.options.advancedOptions.defaultScope
          : DEFAULT_SCOPE
      }`);
```

Let me know if you'd be able to make these changes, or whether you're happy for me to make them on your behalf.

**Comment by srihari93** [comment]
@stevehobbsdev Sorry, for being sparse communication. If you can make the changes, please go ahead. I had to deprioritize this among my other tasks, so I would appreciate if you can take the feature ahead yourself.

**Comment by stevehobbsdev** [comment]
Will do, thanks @srihari93

**Comment by conorcussell** [comment]
If you need an extra pair of hands to get this into the next release, I'd happily make the changes mentioned above @stevehobbsdev

**Comment by stevehobbsdev** [comment]
Thanks @conorcussell. They're already in progress, I just need to push what I have (hopefully tomorrow). Feel free to chime in on a review once they're there 👍

**Comment by stevehobbsdev** [comment]
I could not push changes to this PR, so I have now opened #435 to implement this.

**Pull request closed without merging**
