### PR TITLE
[SDK-1395] Refactor loginWithPopup to optionally accept an existing popup window

### LINKED ISSUE #300: PWA loginWithPopup blocked
### Description
Android pwa can't popup login. I can login in chrome browser on Android. But this app add to home screen can't login with popup. My `manifest.json` is `"display": "standalone"`.

Popup is `about:blank#blocked`.
### Reproduction
On Android version 9
1. App add to home screen.
2. Login with Popup.
3. `about:blank#blocked`

### Environment
Android version 9 
`"@auth0/auth0-spa-js": "^1.2.3"`

### PR DESCRIPTION
**Pull request by stevehobbsdev**
### Description

This PR adds a new option to `loginWithPopup` that would allow the developer to pass an existing popup window to be used instead of the SDK creating its own. This allows the popup to work better in scenarios like on iOS where the popup should be opened inside a button click handler without any async wrappers.

It also allows us to fix an issue where the popup sometimes doesn't work properly inside a PWA. The existing logic creates the pop window and then sets the URL, whereas now in this PR those two steps are unified.

### References

Closes #300 

### Testing

Manually tested by adding a new button to the playground that allows a popup window to be specified when calling `loginWithPopup`. Unit tests have also been added.

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by zewa666** [comment]
worked for me on Android, had no opportunity to test on iOS due to lack of device. But since @charsleysa mentioned doing it this way in his patch I would guess it should work as well.

**Comment by stevehobbsdev** [comment]
@zewa666 Thanks for looking. Can you confirm that it solves your original problem of opening the popup window _without_ the need for a `setTimeout` call?

**Comment by zewa666** [comment]
@stevehobbsdev sorry for being unclear. Yes I've reverted my changes, checked out your branch in my cloned repo, ran `npm run build` and tried it on the phone. It did pass for me

**Comment by stevehobbsdev** [comment]
Thanks @zewa666 !

**Pull request merged**
