### PR TITLE
include polyfill for Set

### PR DESCRIPTION
**Pull request by tony-aq**
### Description

`Set` polyfill for clients which do not have capability to instantiate `Set`.

### Testing

Use library version >= 1.6.0 without `Set` capability:
https://caniuse.com/#search=new%20Set()

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
@tony-aq Thanks for raising. I'm curious as to why we need to include this polyfill as we don't use `Set` ourselves. I would expect the consuming application to include this.

Can you include some repro steps where you're seeing not having this polyfill is causing an issue?

**Comment by tony-aq** [comment]
Hi @stevehobbsdev!
We were using the CDN distribution of auth0-spa-js 1.7.0.  

The build includes a package browser-tabs-lock that uses `Set`:
https://github.com/supertokens/browser-tabs-lock/blob/master/index.ts#L63

You can find this in the auth0-spa-js distribution js by searching for `acquiredIatSet`

So to be clear - this is not a problem with the auth0-spa-js library - but a problem with our usage of the CDN build.

**Comment by stevehobbsdev** [comment]
@tony-aq Thanks for this. I'd like to merge - could you please merge your changes from master or rebase? I don't appear to have permissions on the PR to do this myself.

**Comment by tony-aq** [comment]
@stevehobbsdev thank you for the update!
I merged the master in.

**Comment by nirvdrum** [comment]
Should this change be upstreamed? It seems odd to me that every project depending on _browser-tabs-lock_ is expected to supply its own polyfills.

**Comment by stevehobbsdev** [comment]
I can understand the thinking behind it. We provided the polyfill here because we we do for all the other things we need, so it feels like an omission at this point.

**Pull request merged**
