### PR TITLE
Check for type of MessageEvent source before closing

### PR DESCRIPTION
**Pull request by chrisscott**
Make sure it is a Window before attempting to `close()` it.

Prevents a fatal error when using `getTokenSilently()`.

### CODE REVIEW

**Comment by chrisscott** [comment]
I'm not sure the best way to resolve the tests failing since in practice `e.source.close()` doesn't always exist as `e.source` isn't always a Window object. Simplest seems to remove the tests since we can't guarantee `close()` will always run but I wanted to get feedback before removing them.

**Comment by luisrudge** [comment]
In what case the instance will not be a Window?

**Comment by chrisscott** [comment]
In the browser, I'm seeing it also be `undefined` or `global`.

**Comment by luisrudge** [comment]
@chrisscott can you tell me what are the repro steps for being undefined? Also, what is `global` in this context?

**Comment by chrisscott** [comment]
@luisrudge  I'm seeing `iframeEventHandler()` being called twice when calling `createAuth0Client()`. The first time the former it is called, `e.source` is a Window but the second time it shows as `global` in the debugger. Setting a breakpoint in `iframeEventHandler()` should hopefully show what I'm seeing. 

Semi-related, should the negation in [this conditional check](https://github.com/auth0/auth0-spa-js/blob/master/src/index.ts#L10) not be there? Seems like the intent is to run `getTokenSilently()` when  the user isn't authenticated but this is causing the opposite.

**Comment by luisrudge** [comment]
Can you share a simple project that calls this method twice? I can't repro here.

@chrisscott the `'auth0.is.authenticated'` key is misleading haha.. it should be `'auth0.has.the.user.authenticated.before.?'`

The idea is: if this browser didn't authenticate before (or if the cookie expired), then it makes no sense to call `getTokenSilently`, because it will most likely return `login_required`.

**Comment by chrisscott** [comment]
Thanks for clarifying and suggesting a simple app to test. I did that and I'm unable to reproduce so it must be something happening in the app I've been testing with. Closing this out.

**Pull request closed without merging**
