### PR TITLE
Use user provided params on silent login

### PR DESCRIPTION
**Pull request by nkete**
### Description

This PR adds support for custom query parameters in `getTokenSilently` similar to how `loginWithRedirect` does this.

### References

- [Issue on Github](https://github.com/auth0/auth0-spa-js/issues/317)

### Testing

Add a custom property to the `getTokenSilently` method call and inspect the generated url.
```js
auth0.getTokenSilently({
    scope,
    audience,
    foo: 'bar',
});
```

I was looking at integration tests I noticed that `getTokenSilently > Builds URL correctly` test is skipped. Can someone provide some context on why is that? Should the test be updated to reflect custom parameters as well?

### Checklist

- [x] All active GitHub checks for tests, formatting, and security are passing

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
@nkete Thanks for raising this. Before we bring it in, let me get a look at that integration test which is being skipped and get back to you. You're right, we'll want to update that with your changes if we can.

**Comment by stevehobbsdev** [comment]
@nkete I'm doing some other work on this SDK and in there I've ended up removing the integration test that is being skipped. It was being skipped because it just doesn't work, so I've removed it and taken a different approach. However, it's only available in another branch so I would ignore this test for now.

However, we would require some test coverage around this new functionality you've provided - could you please add those tests to the PR?

**Comment by nkete** [comment]
@stevehobbsdev sure, I'll get back to you once I add the tests.

**Comment by stevehobbsdev** [comment]
Thanks @nkete. To clarify above, when I mentioned "test coverage" I was referring to unit tests. I'd think they'd be enough for this particular case.

**Comment by nkete** [comment]
@stevehobbsdev I added a test for custom params to the `getTokenSilently` section, please take a look if that'll do. Also rebased against latest master.

**Pull request merged**
